// <auto-generated />
using System;
using MacroRegimeFactorMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MacroRegimeFactorMonitor.Data.Migrations;

[DbContext(typeof(MacroRegimeDbContext))]
[Migration("20260509080000_AddFactorScoreMetadata")]
partial class AddFactorScoreMetadata
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        Npgsql.EntityFrameworkCore.PostgreSQL.NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        BuildModel(modelBuilder);
#pragma warning restore 612, 618
    }

    internal static void BuildModel(ModelBuilder modelBuilder)
    {
        AddStartupSyncRuns.BuildModel(modelBuilder);

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.FactorScore", b =>
        {
            var macroFactorId = b.Metadata.FindProperty("MacroFactorId");
            var scoreDate = b.Metadata.FindProperty("ScoreDate");
            if (macroFactorId is not null && scoreDate is not null)
            {
                var oldIndex = b.Metadata.FindIndex(new[] { macroFactorId, scoreDate });
                if (oldIndex is not null)
                {
                    b.Metadata.RemoveIndex(oldIndex);
                }
            }

            b.Property<DateTime?>("CalculatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("CalculationNotes")
                .HasColumnType("text");

            b.Property<string>("DataMode")
                .IsRequired()
                .ValueGeneratedOnAdd()
                .HasMaxLength(40)
                .HasColumnType("character varying(40)")
                .HasDefaultValue("Sample");

            b.Property<string>("RegimeImpact")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("ScoringModelVersion")
                .ValueGeneratedOnAdd()
                .HasMaxLength(80)
                .HasColumnType("character varying(80)")
                .HasDefaultValue("sample-v0");

            b.Property<int>("SourceObservationCount")
                .HasColumnType("integer");

            b.HasIndex("MacroFactorId", "ScoreDate", "DataMode", "ScoringModelVersion")
                .IsUnique();
        });
    }
}
