// <auto-generated />
using System;
using MacroRegimeFactorMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MacroRegimeFactorMonitor.Data.Migrations;

[DbContext(typeof(MacroRegimeDbContext))]
[Migration("20260507120000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        BuildModel(modelBuilder);
#pragma warning restore 612, 618
    }

    internal static void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.FactorScore", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<int>("MacroFactorId")
                .HasColumnType("integer");

            b.Property<string>("Notes")
                .IsRequired()
                .HasColumnType("text");

            b.Property<decimal>("RawScore")
                .HasPrecision(8, 4)
                .HasColumnType("numeric(8,4)");

            b.Property<string>("RegimeImpact")
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnType("character varying(80)");

            b.Property<DateOnly>("ScoreDate")
                .HasColumnType("date");

            b.Property<decimal>("WeightedScore")
                .HasPrecision(8, 4)
                .HasColumnType("numeric(8,4)");

            b.HasKey("Id");

            b.HasIndex("MacroFactorId", "ScoreDate")
                .IsUnique();

            b.ToTable("FactorScores");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.Indicator", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<decimal>("Baseline")
                .HasPrecision(12, 4)
                .HasColumnType("numeric(12,4)");

            b.Property<int>("MacroFactorId")
                .HasColumnType("integer");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("Source")
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnType("character varying(80)");

            b.Property<string>("Unit")
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnType("character varying(40)");

            b.Property<decimal>("Volatility")
                .HasPrecision(12, 4)
                .HasColumnType("numeric(12,4)");

            b.HasKey("Id");

            b.HasIndex("MacroFactorId");

            b.ToTable("Indicators");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.IndicatorObservation", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<int>("IndicatorId")
                .HasColumnType("integer");

            b.Property<string>("Notes")
                .IsRequired()
                .HasColumnType("text");

            b.Property<DateOnly>("ObservationDate")
                .HasColumnType("date");

            b.Property<decimal>("Value")
                .HasPrecision(12, 4)
                .HasColumnType("numeric(12,4)");

            b.HasKey("Id");

            b.HasIndex("IndicatorId", "ObservationDate")
                .IsUnique();

            b.ToTable("IndicatorObservations");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.MacroFactor", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<string>("Category")
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnType("character varying(80)");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("text");

            b.Property<bool>("HigherIsRiskOn")
                .HasColumnType("boolean");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<decimal>("Weight")
                .HasPrecision(8, 4)
                .HasColumnType("numeric(8,4)");

            b.HasKey("Id");

            b.HasIndex("Name")
                .IsUnique();

            b.ToTable("MacroFactors");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.TradeIdea", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<string>("Catalyst")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("EntryTrigger")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<DateOnly>("IdeaDate")
                .HasColumnType("date");

            b.Property<string>("Instrument")
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnType("character varying(80)");

            b.Property<string>("Invalidation")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<string>("MaxLoss")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("PostMortem")
                .IsRequired()
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<string>("RiskNotes")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnType("character varying(40)");

            b.Property<string>("Thesis")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("TimeHorizon")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(160)
                .HasColumnType("character varying(160)");

            b.HasKey("Id");

            b.ToTable("TradeIdeas");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.WeeklyReview", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("KeyDevelopments")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("RegimeAssessment")
                .IsRequired()
                .HasMaxLength(120)
                .HasColumnType("character varying(120)");

            b.Property<string>("RisksToWatch")
                .IsRequired()
                .HasColumnType("text");

            b.Property<DateOnly>("WeekEnding")
                .HasColumnType("date");

            b.HasKey("Id");

            b.HasIndex("WeekEnding")
                .IsUnique();

            b.ToTable("WeeklyReviews");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.FactorScore", b =>
        {
            b.HasOne("MacroRegimeFactorMonitor.Domain.MacroFactor", "MacroFactor")
                .WithMany("Scores")
                .HasForeignKey("MacroFactorId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("MacroFactor");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.Indicator", b =>
        {
            b.HasOne("MacroRegimeFactorMonitor.Domain.MacroFactor", "MacroFactor")
                .WithMany("Indicators")
                .HasForeignKey("MacroFactorId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("MacroFactor");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.IndicatorObservation", b =>
        {
            b.HasOne("MacroRegimeFactorMonitor.Domain.Indicator", "Indicator")
                .WithMany("Observations")
                .HasForeignKey("IndicatorId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Indicator");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.Indicator", b =>
        {
            b.Navigation("Observations");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.MacroFactor", b =>
        {
            b.Navigation("Indicators");
            b.Navigation("Scores");
        });
    }
}
