// <auto-generated />
using System;
using MacroRegimeFactorMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MacroRegimeFactorMonitor.Data.Migrations;

[DbContext(typeof(MacroRegimeDbContext))]
[Migration("20260509120000_AddFactorScoreDiagnostics")]
partial class AddFactorScoreDiagnostics
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        BuildModel(modelBuilder);
#pragma warning restore 612, 618
    }

    internal static void BuildModel(ModelBuilder modelBuilder)
    {
        AddFactorScoreMetadata.BuildModel(modelBuilder);

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.FactorScore", b =>
        {
            b.Property<string>("DataQualityNotes")
                .HasColumnType("text");

            b.Property<string>("DataQualityStatus")
                .HasMaxLength(40)
                .HasColumnType("character varying(40)");

            b.Property<int?>("DaysSinceSourceObservation")
                .HasColumnType("integer");

            b.Property<decimal?>("ObservationChange")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<decimal?>("ObservationChangePercent")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<DateOnly?>("PreviousObservationDate")
                .HasColumnType("date");

            b.Property<decimal?>("PreviousObservationValue")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<DateOnly?>("SourceObservationDate")
                .HasColumnType("date");

            b.Property<decimal?>("SourceObservationValue")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");
        });
    }
}
