// <auto-generated />
using System;
using MacroRegimeFactorMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MacroRegimeFactorMonitor.Data.Migrations;

[DbContext(typeof(MacroRegimeDbContext))]
[Migration("20260509143000_AddFactorScoreWindowDiagnostics")]
partial class AddFactorScoreWindowDiagnostics
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        BuildModel(modelBuilder);
#pragma warning restore 612, 618
    }

    internal static void BuildModel(ModelBuilder modelBuilder)
    {
        AddFactorScoreDiagnostics.BuildModel(modelBuilder);

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.FactorScore", b =>
        {
            b.Property<string>("ScoringConfidence")
                .HasMaxLength(40)
                .HasColumnType("character varying(40)");

            b.Property<string>("ScoringConfidenceNotes")
                .HasColumnType("text");

            b.Property<decimal?>("WindowAcceleration")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<decimal?>("WindowAverageValue")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<decimal?>("WindowChange")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<decimal?>("WindowChangePercent")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<DateOnly?>("WindowEndDate")
                .HasColumnType("date");

            b.Property<decimal?>("WindowFirstValue")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<decimal?>("WindowLastValue")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<decimal?>("WindowMaxValue")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<decimal?>("WindowMinValue")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<int?>("WindowObservationCount")
                .HasColumnType("integer");

            b.Property<decimal?>("WindowSlope")
                .HasPrecision(18, 6)
                .HasColumnType("numeric(18,6)");

            b.Property<DateOnly?>("WindowStartDate")
                .HasColumnType("date");
        });
    }
}
