// <auto-generated />
using System;
using MacroRegimeFactorMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MacroRegimeFactorMonitor.Data.Migrations;

[DbContext(typeof(MacroRegimeDbContext))]
[Migration("20260507133000_AddDataIngestionFoundation")]
partial class AddDataIngestionFoundation
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        BuildModel(modelBuilder);
#pragma warning restore 612, 618
    }

    internal static void BuildModel(ModelBuilder modelBuilder)
    {
        InitialCreate.BuildModel(modelBuilder);

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.DataSource", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<string>("BaseUrl").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true);
            b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<string>("Notes").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("");
            b.Property<bool>("RequiresApiKey").HasColumnType("boolean");
            b.Property<string>("SourceType").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
            b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.ToTable("DataSources");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.DataImportRun", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<int>("DataSourceId").HasColumnType("integer");
            b.Property<string>("ErrorMessage").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("");
            b.Property<DateTime?>("FinishedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Notes").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("");
            b.Property<int>("RowsInserted").HasColumnType("integer");
            b.Property<int>("RowsRead").HasColumnType("integer");
            b.Property<int>("RowsUpdated").HasColumnType("integer");
            b.Property<DateTime>("StartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.HasKey("Id");
            b.HasIndex("DataSourceId", "StartedAtUtc");
            b.HasIndex("Status");
            b.ToTable("DataImportRuns");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.ExternalSeries", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<int>("DataSourceId").HasColumnType("integer");
            b.Property<string>("Endpoint").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.Property<string>("ExternalSeriesId").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
            b.Property<string>("Frequency").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.Property<int>("IndicatorId").HasColumnType("integer");
            b.Property<bool>("IsActive").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true);
            b.Property<DateTime?>("LastSuccessfulImportUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Notes").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("");
            b.Property<string>("ObservationDateField").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.Property<string>("Transform").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.Property<string>("Units").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("ValueField").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.HasKey("Id");
            b.HasIndex("DataSourceId");
            b.HasIndex("IndicatorId");
            b.HasIndex("DataSourceId", "ExternalSeriesId", "IndicatorId").IsUnique();
            b.ToTable("ExternalSeries");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.IndicatorObservation", b =>
        {
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<int?>("DataImportRunId").HasColumnType("integer");
            b.Property<int?>("ExternalSeriesId").HasColumnType("integer");
            b.Property<string>("Source").IsRequired().ValueGeneratedOnAdd().HasMaxLength(120).HasColumnType("character varying(120)").HasDefaultValue("");
            b.Property<DateOnly?>("SourceReleaseDate").HasColumnType("date");
            b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<DateOnly?>("VintageDate").HasColumnType("date");
            b.HasIndex("DataImportRunId");
            b.HasIndex("ExternalSeriesId");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.DataImportRun", b =>
        {
            b.HasOne("MacroRegimeFactorMonitor.Domain.DataSource", "DataSource")
                .WithMany("ImportRuns").HasForeignKey("DataSourceId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("DataSource");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.ExternalSeries", b =>
        {
            b.HasOne("MacroRegimeFactorMonitor.Domain.DataSource", "DataSource")
                .WithMany("ExternalSeries").HasForeignKey("DataSourceId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("MacroRegimeFactorMonitor.Domain.Indicator", "Indicator")
                .WithMany("ExternalSeries").HasForeignKey("IndicatorId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("DataSource");
            b.Navigation("Indicator");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.IndicatorObservation", b =>
        {
            b.HasOne("MacroRegimeFactorMonitor.Domain.DataImportRun", "DataImportRun")
                .WithMany("Observations").HasForeignKey("DataImportRunId").OnDelete(DeleteBehavior.SetNull);
            b.HasOne("MacroRegimeFactorMonitor.Domain.ExternalSeries", "ExternalSeries")
                .WithMany("Observations").HasForeignKey("ExternalSeriesId").OnDelete(DeleteBehavior.SetNull);
            b.Navigation("DataImportRun");
            b.Navigation("ExternalSeries");
        });

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.DataImportRun", b => b.Navigation("Observations"));
        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.DataSource", b =>
        {
            b.Navigation("ExternalSeries");
            b.Navigation("ImportRuns");
        });
        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.ExternalSeries", b => b.Navigation("Observations"));
        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.Indicator", b => b.Navigation("ExternalSeries"));
    }
}
