// <auto-generated />
using System;
using MacroRegimeFactorMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MacroRegimeFactorMonitor.Data.Migrations;

[DbContext(typeof(MacroRegimeDbContext))]
[Migration("20260507143000_AddStartupSyncRuns")]
partial class AddStartupSyncRuns
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        BuildModel(modelBuilder);
#pragma warning restore 612, 618
    }

    internal static void BuildModel(ModelBuilder modelBuilder)
    {
        AddDataIngestionFoundation.BuildModel(modelBuilder);

        modelBuilder.Entity("MacroRegimeFactorMonitor.Domain.StartupSyncRun", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            b.Property<string>("AppliedMigrations").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("");
            b.Property<string>("ErrorMessage").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("");
            b.Property<DateTime?>("FinishedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Message").IsRequired().ValueGeneratedOnAdd().HasColumnType("text").HasDefaultValue("");
            b.Property<int>("SeededDataSources").HasColumnType("integer");
            b.Property<int>("SeededFactorScores").HasColumnType("integer");
            b.Property<int>("SeededIndicators").HasColumnType("integer");
            b.Property<int>("SeededMacroFactors").HasColumnType("integer");
            b.Property<int>("SeededObservations").HasColumnType("integer");
            b.Property<int>("SeededTradeIdeas").HasColumnType("integer");
            b.Property<int>("SeededWeeklyReviews").HasColumnType("integer");
            b.Property<DateTime>("StartedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Status").IsRequired().HasMaxLength(40).HasColumnType("character varying(40)");
            b.HasKey("Id");
            b.HasIndex("StartedAtUtc");
            b.HasIndex("Status");
            b.ToTable("StartupSyncRuns");
        });
    }
}
